name: Robot SmartSelect Tu Dong
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install requests
      - run: python crawl_xo_so.py
      - name: Day file len GitHub
        run: |
          git config --global user.name "Robot SmartSelect"
          git config --global user.email "robot@smartselect.com"
          git add ketqua.csv
          git commit -m "Cap nhat ket qua" || exit 0
          git push origin main --force
